/*
 * This file is generated by jOOQ.
 */
package com.sunnymix.doccap.dao.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Block implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String  id;
    private final String  docId;
    private final String  source;
    private final Integer pos;

    public Block(Block value) {
        this.id = value.id;
        this.docId = value.docId;
        this.source = value.source;
        this.pos = value.pos;
    }

    public Block(
        String  id,
        String  docId,
        String  source,
        Integer pos
    ) {
        this.id = id;
        this.docId = docId;
        this.source = source;
        this.pos = pos;
    }

    /**
     * Getter for <code>doccap.block.id</code>. ID
     */
    public String getId() {
        return this.id;
    }

    /**
     * Getter for <code>doccap.block.doc_id</code>. 文档ID
     */
    public String getDocId() {
        return this.docId;
    }

    /**
     * Getter for <code>doccap.block.source</code>. 内容
     */
    public String getSource() {
        return this.source;
    }

    /**
     * Getter for <code>doccap.block.pos</code>. 位置
     */
    public Integer getPos() {
        return this.pos;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Block (");

        sb.append(id);
        sb.append(", ").append(docId);
        sb.append(", ").append(source);
        sb.append(", ").append(pos);

        sb.append(")");
        return sb.toString();
    }
}
