/*
 * This file is generated by jOOQ.
 */
package com.sunnymix.doccap.dao.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Block implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String  id;
    private final String  docId;
    private final String  text;
    private final Integer pos;

    public Block(Block value) {
        this.id = value.id;
        this.docId = value.docId;
        this.text = value.text;
        this.pos = value.pos;
    }

    public Block(
        String  id,
        String  docId,
        String  text,
        Integer pos
    ) {
        this.id = id;
        this.docId = docId;
        this.text = text;
        this.pos = pos;
    }

    /**
     * Getter for <code>doccap.block.id</code>. ID
     */
    public String getId() {
        return this.id;
    }

    /**
     * Getter for <code>doccap.block.doc_id</code>. 文档ID
     */
    public String getDocId() {
        return this.docId;
    }

    /**
     * Getter for <code>doccap.block.text</code>. 内容
     */
    public String getText() {
        return this.text;
    }

    /**
     * Getter for <code>doccap.block.pos</code>. 位置
     */
    public Integer getPos() {
        return this.pos;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Block (");

        sb.append(id);
        sb.append(", ").append(docId);
        sb.append(", ").append(text);
        sb.append(", ").append(pos);

        sb.append(")");
        return sb.toString();
    }
}
