/*
 * This file is generated by jOOQ.
 */
package com.sunnymix.wingdoc.dao.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Block implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String  id;
    private final String  docId;
    private final Integer pos;
    private final String  type;
    private final String  status;
    private final String  text;
    private final String  link;

    public Block(Block value) {
        this.id = value.id;
        this.docId = value.docId;
        this.pos = value.pos;
        this.type = value.type;
        this.status = value.status;
        this.text = value.text;
        this.link = value.link;
    }

    public Block(
        String  id,
        String  docId,
        Integer pos,
        String  type,
        String  status,
        String  text,
        String  link
    ) {
        this.id = id;
        this.docId = docId;
        this.pos = pos;
        this.type = type;
        this.status = status;
        this.text = text;
        this.link = link;
    }

    /**
     * Getter for <code>wingdoc.block.id</code>. ID
     */
    public String getId() {
        return this.id;
    }

    /**
     * Getter for <code>wingdoc.block.doc_id</code>. 文档ID
     */
    public String getDocId() {
        return this.docId;
    }

    /**
     * Getter for <code>wingdoc.block.pos</code>. 位置
     */
    public Integer getPos() {
        return this.pos;
    }

    /**
     * Getter for <code>wingdoc.block.type</code>. 类型
     */
    public String getType() {
        return this.type;
    }

    /**
     * Getter for <code>wingdoc.block.status</code>. 状态
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Getter for <code>wingdoc.block.text</code>. 内容
     */
    public String getText() {
        return this.text;
    }

    /**
     * Getter for <code>wingdoc.block.link</code>. 链接
     */
    public String getLink() {
        return this.link;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Block (");

        sb.append(id);
        sb.append(", ").append(docId);
        sb.append(", ").append(pos);
        sb.append(", ").append(type);
        sb.append(", ").append(status);
        sb.append(", ").append(text);
        sb.append(", ").append(link);

        sb.append(")");
        return sb.toString();
    }
}
