/*
 * This file is generated by jOOQ.
 */
package com.sunnymix.wingdoc.dao.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Doc implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String id;
    private final String title;
    private final String author;

    public Doc(Doc value) {
        this.id = value.id;
        this.title = value.title;
        this.author = value.author;
    }

    public Doc(
        String id,
        String title,
        String author
    ) {
        this.id = id;
        this.title = title;
        this.author = author;
    }

    /**
     * Getter for <code>wingdoc.doc.id</code>. ID
     */
    public String getId() {
        return this.id;
    }

    /**
     * Getter for <code>wingdoc.doc.title</code>. 标题
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Getter for <code>wingdoc.doc.author</code>. 作者
     */
    public String getAuthor() {
        return this.author;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Doc (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(author);

        sb.append(")");
        return sb.toString();
    }
}
