/*
 * This file is generated by jOOQ.
 */
package com.sunnymix.wingdoc.dao.jooq;


import com.sunnymix.wingdoc.dao.jooq.tables.Doc;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in wingdoc.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index DOC_IDX_TITLE = Internal.createIndex(DSL.name("idx_title"), Doc.DOC, new OrderField[] { Doc.DOC.TITLE }, false);
}
