/*
 * This file is generated by jOOQ.
 */
package com.sunnymix.wingdoc.dao.jooq;


import com.sunnymix.wingdoc.dao.jooq.tables.Block;
import com.sunnymix.wingdoc.dao.jooq.tables.Doc;
import com.sunnymix.wingdoc.dao.jooq.tables.Mark;


/**
 * Convenience access to all tables in wingdoc.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>wingdoc.block</code>.
     */
    public static final Block BLOCK = Block.BLOCK;

    /**
     * The table <code>wingdoc.doc</code>.
     */
    public static final Doc DOC = Doc.DOC;

    /**
     * The table <code>wingdoc.mark</code>.
     */
    public static final Mark MARK = Mark.MARK;
}
