/*
 * This file is generated by jOOQ.
 */
package com.sunnymix.wingdoc.dao.jooq;


import com.sunnymix.wingdoc.dao.jooq.tables.Block;
import com.sunnymix.wingdoc.dao.jooq.tables.Doc;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Wingdoc extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>wingdoc</code>
     */
    public static final Wingdoc WINGDOC = new Wingdoc();

    /**
     * The table <code>wingdoc.block</code>.
     */
    public final Block BLOCK = Block.BLOCK;

    /**
     * The table <code>wingdoc.doc</code>.
     */
    public final Doc DOC = Doc.DOC;

    /**
     * No further instances allowed
     */
    private Wingdoc() {
        super("wingdoc", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Block.BLOCK,
            Doc.DOC
        );
    }
}
