/*
 * This file is generated by jOOQ.
 */
package com.sunnymix.doccap.dao.jooq;


import com.sunnymix.doccap.dao.jooq.tables.Doc;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Doccap extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>doccap</code>
     */
    public static final Doccap DOCCAP = new Doccap();

    /**
     * The table <code>doccap.doc</code>.
     */
    public final Doc DOC = Doc.DOC;

    /**
     * No further instances allowed
     */
    private Doccap() {
        super("doccap", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Doc.DOC
        );
    }
}
