/*
 * This file is generated by jOOQ.
 */
package com.sunnymix.doccap.dao.jooq;


import com.sunnymix.doccap.dao.jooq.tables.Doc;
import com.sunnymix.doccap.dao.jooq.tables.records.DocRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * doccap.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DocRecord> KEY_DOC_PRIMARY = Internal.createUniqueKey(Doc.DOC, DSL.name("KEY_doc_PRIMARY"), new TableField[] { Doc.DOC.ID }, true);
}
