/*
 * This file is generated by jOOQ.
 */
package com.sunnymix.doccap.dao.jooq;


import com.sunnymix.doccap.dao.jooq.tables.Block;
import com.sunnymix.doccap.dao.jooq.tables.Doc;


/**
 * Convenience access to all tables in doccap.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>doccap.block</code>.
     */
    public static final Block BLOCK = Block.BLOCK;

    /**
     * The table <code>doccap.doc</code>.
     */
    public static final Doc DOC = Doc.DOC;
}
