/*
 * This file is generated by jOOQ.
 */
package com.sunnymix.wingdoc.dao.jooq.tables.records;


import com.sunnymix.wingdoc.dao.jooq.tables.Mark;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MarkRecord extends UpdatableRecordImpl<MarkRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>wingdoc.mark.id</code>.
     */
    public MarkRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>wingdoc.mark.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>wingdoc.mark.doc_id</code>. 文档ID
     */
    public MarkRecord setDocId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>wingdoc.mark.doc_id</code>. 文档ID
     */
    public String getDocId() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Mark.MARK.ID;
    }

    @Override
    public Field<String> field2() {
        return Mark.MARK.DOC_ID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getDocId();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getDocId();
    }

    @Override
    public MarkRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public MarkRecord value2(String value) {
        setDocId(value);
        return this;
    }

    @Override
    public MarkRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MarkRecord
     */
    public MarkRecord() {
        super(Mark.MARK);
    }

    /**
     * Create a detached, initialised MarkRecord
     */
    public MarkRecord(Integer id, String docId) {
        super(Mark.MARK);

        setId(id);
        setDocId(docId);
    }

    /**
     * Create a detached, initialised MarkRecord
     */
    public MarkRecord(com.sunnymix.wingdoc.dao.jooq.tables.pojos.Mark value) {
        super(Mark.MARK);

        if (value != null) {
            setId(value.getId());
            setDocId(value.getDocId());
        }
    }
}
