/*
 * This file is generated by jOOQ.
 */
package com.sunnymix.wingdoc.dao.jooq.tables.records;


import com.sunnymix.wingdoc.dao.jooq.tables.Mark;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MarkRecord extends UpdatableRecordImpl<MarkRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>wingdoc.mark.id</code>.
     */
    public MarkRecord setId(Integer value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>wingdoc.mark.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>wingdoc.mark.doc_id</code>. 文档ID
     */
    public MarkRecord setDocId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>wingdoc.mark.doc_id</code>. 文档ID
     */
    public String getDocId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>wingdoc.mark.pin</code>.
     */
    public MarkRecord setPin(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>wingdoc.mark.pin</code>.
     */
    public Integer getPin() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Mark.MARK.ID;
    }

    @Override
    public Field<String> field2() {
        return Mark.MARK.DOC_ID;
    }

    @Override
    public Field<Integer> field3() {
        return Mark.MARK.PIN;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getDocId();
    }

    @Override
    public Integer component3() {
        return getPin();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getDocId();
    }

    @Override
    public Integer value3() {
        return getPin();
    }

    @Override
    public MarkRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public MarkRecord value2(String value) {
        setDocId(value);
        return this;
    }

    @Override
    public MarkRecord value3(Integer value) {
        setPin(value);
        return this;
    }

    @Override
    public MarkRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MarkRecord
     */
    public MarkRecord() {
        super(Mark.MARK);
    }

    /**
     * Create a detached, initialised MarkRecord
     */
    public MarkRecord(Integer id, String docId, Integer pin) {
        super(Mark.MARK);

        setId(id);
        setDocId(docId);
        setPin(pin);
    }

    /**
     * Create a detached, initialised MarkRecord
     */
    public MarkRecord(com.sunnymix.wingdoc.dao.jooq.tables.pojos.Mark value) {
        super(Mark.MARK);

        if (value != null) {
            setId(value.getId());
            setDocId(value.getDocId());
            setPin(value.getPin());
        }
    }
}
